"""create teams players games settings tables

Revision ID: 52c67ba45532
Revises: 
Create Date: 2026-08-23 17:51:56.031915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52c67ba45532'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_note_multiplier', sa.Float(), nullable=False),
    sa.Column('per_impact_multiplier', sa.Float(), nullable=False),
    sa.Column('back_to_back_penalty', sa.Float(), nullable=False),
    sa.Column('three_in_four_penalty', sa.Float(), nullable=False),
    sa.Column('mpg_threshold', sa.Float(), nullable=False),
    sa.Column('draft_bonus_config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=5), nullable=False),
    sa.Column('conference', sa.String(length=20), nullable=True),
    sa.Column('division', sa.String(length=30), nullable=True),
    sa.Column('win_pct_home', sa.Float(), nullable=False),
    sa.Column('win_pct_away', sa.Float(), nullable=False),
    sa.Column('win_pct_home_prev_season', sa.Float(), nullable=False),
    sa.Column('win_pct_away_prev_season', sa.Float(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'FINISHED', 'POSTPONED', name='gamestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('previous_team_id', sa.Integer(), nullable=True),
    sa.Column('per', sa.Float(), nullable=False),
    sa.Column('mpg', sa.Float(), nullable=False),
    sa.Column('injury_status', sa.Enum('HEALTHY', 'OUT', 'QUESTIONABLE', 'DOUBTFUL', name='injurystatus'), nullable=False),
    sa.Column('injury_updated_at', sa.DateTime(), nullable=True),
    sa.Column('draft_pick', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['previous_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('settings')
    # ### end Alembic commands ###
