"""add previous_season_player_stats, transfer_impact_multiplier, draft import type

Revision ID: 8f6de85f79e4
Revises: c20e7795f1be
Create Date: 2026-08-24 20:03:25.984868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f6de85f79e4'
down_revision: Union[str, None] = 'c20e7795f1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previous_season_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=9), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('team_abbreviation', sa.String(length=5), nullable=False),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('mpg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'player_name', name='uq_prev_season_player')
    )
    op.add_column(
        'import_history',
        sa.Column(
            'season_type',
            sa.Enum('CURRENT', 'PREVIOUS', name='seasontype'),
            server_default='CURRENT',
            nullable=False,
        ),
    )
    op.add_column('import_history', sa.Column('season', sa.String(length=9), nullable=True))
    op.add_column(
        'settings',
        sa.Column('transfer_impact_multiplier', sa.Float(), server_default='0.4', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'transfer_impact_multiplier')
    op.drop_column('import_history', 'season')
    op.drop_column('import_history', 'season_type')
    op.drop_table('previous_season_player_stats')
    # ### end Alembic commands ###
