"""add import_history table and extend injury status enum

Revision ID: 94a6b85b00fe
Revises: 52c67ba45532
Create Date: 2026-08-23 20:20:20.860842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a6b85b00fe'
down_revision: Union[str, None] = '52c67ba45532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_type', sa.Enum('TEAMS_HOME_AWAY', 'PLAYERS_ADVANCED', 'PLAYERS_PER_GAME', name='importtype'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'PARTIAL', 'ERROR', name='importstatus'), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_history')
    # ### end Alembic commands ###
