"""add injury_reason to players

Revision ID: c20e7795f1be
Revises: f4f99df21e8a
Create Date: 2026-08-23 21:52:36.214463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20e7795f1be'
down_revision: Union[str, None] = 'f4f99df21e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('injury_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'injury_reason')
    # ### end Alembic commands ###
